### ISSUE TITLE
powershell template EICAR特征

### ISSUE THREAD

**Issue by scanfsec** [Lz1y/cobalt_strike_3.12_patch#1]
/resources/template.x86.ps1
/resources/template.x64.ps1
![image](https://user-images.githubusercontent.com/8190138/47196787-e5debb00-d394-11e8-8445-2ceb8b345005.png)

**Comment by Lz1y** [comment]
收到，记录下来了！感谢提出，有时间就更新

**Comment by Lz1y** [comment]
已经删除，更新了
